import type { PitoletDocument, NodeId } from '@pitolet/schema';
import { componentFileImports, generateComponent } from './component.js';
import {
  componentName,
  componentNameForId,
  componentNames,
  nodeToJsx,
  type JsxOptions,
} from './jsx.js';
import { nodeToHtml } from './html.js';
import { safeCommentValue } from './safety.js';
import { importedFontFaceCss } from './fontFaces.js';
import { generateThemeCss } from './theme.js';

export type CodegenTarget = 'react-tailwind' | 'html';

export interface GeneratedFile {
  path: string;
  contents: string;
  /** The frame/component node this file was generated from (repo linking). */
  sourceId?: string;
}

/** Generate code for one subtree (the Code panel / MCP get_design_as_code). */
export function generateSelection(
  doc: PitoletDocument,
  nodeId: NodeId,
  target: CodegenTarget,
  options: JsxOptions = {},
): string {
  if (target === 'html') {
    const { html, css } = nodeToHtml(doc, nodeId);
    const stylesheet = [importedFontFaceCss(doc.assets), css].filter(Boolean).join('\n\n');
    return `${html}\n\n<style>\n${stylesheet}\n</style>\n`;
  }
  return generateReactSelection(doc, nodeId, options);
}

function generateReactSelection(
  doc: PitoletDocument,
  nodeId: NodeId,
  options: JsxOptions,
  explicitName?: string,
): string {
  const node = doc.nodes[nodeId];
  const importedComponents = componentFileImports(doc, nodeId);
  const importedNames = new Set(importedComponents);
  const baseName = node ? componentName(node.name) : 'Component';
  let name = explicitName ?? baseName;
  let suffix = 1;
  while (!explicitName && importedNames.has(name)) {
    suffix += 1;
    name = suffix === 2 ? `${baseName}Selection` : `${baseName}Selection${suffix - 1}`;
  }
  const annotation = options.annotate
    ? `// @pitolet doc=${safeCommentValue(doc.id)} frame=${safeCommentValue(nodeId)}\n`
    : '';
  const imports = importedComponents
    .map((n) => `import { ${n} } from '../components/${n}';\n`)
    .join('');
  const jsx = nodeToJsx(doc, nodeId, options);
  const header = `${annotation}${imports}${annotation || imports ? '\n' : ''}`;
  return `${header}export function ${name}() {\n  return (\n${indent(jsx, 2)}\n  );\n}\n`;
}

/** Full project export: one component file per root frame + theme.css. */
export function generateProject(doc: PitoletDocument, options: JsxOptions = {}): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  files.push({
    path: 'theme.css',
    contents: generateThemeCss(doc.tokens, doc.breakpoints, doc.assets),
  });
  const names = componentNames(doc);

  for (const def of Object.values(doc.components)) {
    const annotation = options.annotate
      ? `// @pitolet doc=${safeCommentValue(doc.id)} component=${safeCommentValue(def.id)} master=${safeCommentValue(def.rootId)}\n`
      : '';
    files.push({
      path: `components/${names.get(def.id) ?? componentNameForId(doc, def.id)}.tsx`,
      contents: annotation + generateComponent(doc, def),
      sourceId: def.rootId,
    });
  }

  const usedNames = new Set<string>();
  for (const frameId of doc.rootOrder) {
    const frame = doc.nodes[frameId];
    if (!frame || frame.type !== 'frame' || frame.isComponentMaster) continue;
    const base = componentName(frame.name);
    let name = base;
    let suffix = 2;
    const importedNames = new Set(componentFileImports(doc, frameId));
    while (usedNames.has(name) || importedNames.has(name)) name = `${base}${suffix++}`;
    usedNames.add(name);
    files.push({
      path: `frames/${name}.tsx`,
      contents: generateReactSelection(doc, frameId, options, name),
      sourceId: frameId,
    });
  }

  files.push({
    path: 'README.md',
    contents:
      `# ${escapeMarkdown(doc.name)}\n\nGenerated by Pitolet.\n\n` +
      `- \`theme.css\`: design tokens as Tailwind v4 \`@theme\` variables. Import it in your global stylesheet.\n` +
      `- \`frames/\`: one React component per frame, styled with Tailwind classes driven by the theme.\n\n` +
      (Object.keys(doc.assets).length > 0
        ? `- \`assets/\`: local images referenced with \`new URL(..., import.meta.url)\`, which Vite and other ESM-aware bundlers copy into their output.\n\n`
        : '') +
      `Requires Tailwind CSS v4 (\`@import 'tailwindcss'\` is included in theme.css).\n`,
  });

  return files;
}

function escapeMarkdown(value: string): string {
  return value
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/[\r\n]+/g, ' ');
}

function indent(text: string, levels: number): string {
  const pad = '  '.repeat(levels);
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n');
}
