import type { PitoletDocument, NodeId } from '@pitolet/schema';
import { componentFileImports, generateComponent } from './component.js';
import { componentName, nodeToJsx, type JsxOptions } from './jsx.js';
import { nodeToHtml } from './html.js';
import { generateThemeCss } from './theme.js';

export type CodegenTarget = 'react-tailwind' | 'html';

export interface GeneratedFile {
  path: string;
  contents: string;
  /** The frame/component node this file was generated from (repo linking). */
  sourceId?: string;
}

/** Generate code for one subtree (the Code panel / MCP get_design_as_code). */
export function generateSelection(
  doc: PitoletDocument,
  nodeId: NodeId,
  target: CodegenTarget,
  options: JsxOptions = {},
): string {
  if (target === 'html') {
    const { html, css } = nodeToHtml(doc, nodeId);
    return `${html}\n\n<style>\n${css}\n</style>\n`;
  }
  const node = doc.nodes[nodeId];
  const name = node ? componentName(node.name) : 'Component';
  const annotation = options.annotate ? `// @pitolet doc=${doc.id} frame=${nodeId}\n` : '';
  const imports = componentFileImports(doc, nodeId)
    .map((n) => `import { ${n} } from '../components/${n}';\n`)
    .join('');
  const jsx = nodeToJsx(doc, nodeId, options);
  const header = `${annotation}${imports}${annotation || imports ? '\n' : ''}`;
  return `${header}export function ${name}() {\n  return (\n${indent(jsx, 2)}\n  );\n}\n`;
}

/** Full project export: one component file per root frame + theme.css. */
export function generateProject(
  doc: PitoletDocument,
  options: JsxOptions = {},
): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  files.push({ path: 'theme.css', contents: generateThemeCss(doc.tokens) });

  for (const def of Object.values(doc.components)) {
    const annotation = options.annotate
      ? `// @pitolet doc=${doc.id} component=${def.id} master=${def.rootId}\n`
      : '';
    files.push({
      path: `components/${componentName(def.name)}.tsx`,
      contents: annotation + generateComponent(doc, def),
      sourceId: def.rootId,
    });
  }

  const usedNames = new Set<string>();
  for (const frameId of doc.rootOrder) {
    const frame = doc.nodes[frameId];
    if (!frame || frame.type !== 'frame' || frame.isComponentMaster) continue;
    let name = componentName(frame.name);
    while (usedNames.has(name)) name = `${name}2`;
    usedNames.add(name);
    files.push({
      path: `frames/${name}.tsx`,
      contents: generateSelection(doc, frameId, 'react-tailwind', options),
      sourceId: frameId,
    });
  }

  files.push({
    path: 'README.md',
    contents:
      `# ${doc.name}\n\nGenerated by Pitolet.\n\n` +
      `- \`theme.css\`: design tokens as Tailwind v4 \`@theme\` variables. Import it in your global stylesheet.\n` +
      `- \`frames/\`: one React component per frame, styled with Tailwind classes driven by the theme.\n\n` +
      `Requires Tailwind CSS v4 (\`@import 'tailwindcss'\` is included in theme.css).\n`,
  });

  return files;
}

function indent(text: string, levels: number): string {
  const pad = '  '.repeat(levels);
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n');
}
